export const ADD_QUESTION = 'QUESTION/ADD_QUESTION';
export const UPDATE_QUESTION_TEXT = 'QUESTION/UPDATE_QUESTION_TEXT';
export const CHANGE_ANSWER_TYPE = 'QUESTION/CHANGE_ANSWER_TYPE';
export const REMOVE_QUESTION = 'QUESTION/REMOVE_QUESTION';
export const ADD_ANSWER = 'ANSWER/ADD_ANSWER';
export const UPDATE_ANSWER_TEXT = 'ANSWER/UPDATE_ANSWER_TEXT';
export const UPDATE_IS_CORRECT = 'ANSWER/UPDATE_IS_CORRECT';
export const REMOVE_ANSWER = 'ANSWER/REMOVE_ANSWER';
