export const ADD_ANSWER = 'ANSWER/ADD_ANSWER';
export const UPDATE_ANSWER_TEXT = 'ANSWER/UPDATE_ANSWER_TEXT';
export const UPDATE_IS_CORRECT = 'ANSWER/UPDATE_IS_CORRECT';
export const REMOVE_ANSWER = 'ANSWER/REMOVE_ANSWER';
