export const ADD_ANSWER_STARTED = 'ANSWER/ADD_ANSWER_STARTED';
export const ADD_ANSWER_SUCCESS = 'ANSWER/ADD_ANSWER_SUCCESS';
export const ADD_ANSWER_FAILURE = 'ANSWER/ADD_ANSWER_FAILURE';
export const UPDATE_ANSWER_TEXT_SUCCESS = 'ANSWER/UPDATE_ANSWER_TEXT_SUCCESS';
export const UPDATE_IS_CORRECT_SUCCESS = 'ANSWER/UPDATE_IS_CORRECT_SUCCESS';
export const REMOVE_ANSWER_STARTED = 'ANSWER/REMOVE_ANSWER_STARTED';
export const REMOVE_ANSWER_SUCCESS = 'ANSWER/REMOVE_ANSWER_SUCCESS';
export const REMOVE_ANSWER_FAILURE = 'ANSWER/REMOVE_ANSWER_FAILURE';
