export const GET_FORM_STARTED = 'FORM/GET_FORM_STARTED';
export const GET_FORM_SUCCESS = 'FORM/GET_FORM_SUCCESS';
export const GET_FORM_FAILURE = 'FORM/GET_FORM_FAILURE';
export const UPDATE_FORM_TEXT_SUCCESS = 'FORM/UPDATE_FORM_TEXT_SUCCESS';
export const CLEAN_FORM = 'FORM/CLEAN_FORM';
