export const GET_FORMS_LIST_SUCCESS = 'FORMS_LIST/GET_FORMS_LIST_SUCCESS';
export const GET_FORMS_LIST_STARTED = 'FORMS_LIST/GET_FORMS_LIST_STARTED';
export const GET_FORMS_LIST_FAILURE = 'FORMS_LIST/GET_FORMS_LIST_FAILURE';
export const DELETE_FORM_STARTED = 'FORMS_LIST/DELETE_FORM_STARTED';
export const DELETE_FORM_SUCCESS = 'FORMS_LIST/DELETE_FORM_SUCCESS';
export const DELETE_FORM_FAILURE = 'FORMS_LIST/DELETE_FORM_FAILURE';
