export const ADD_QUESTION = 'QUESTION/ADD_QUESTION';
export const UPDATE_QUESTION_TEXT = 'QUESTION/UPDATE_QUESTION_TEXT';
export const CHANGE_ANSWER_TYPE = 'QUESTION/CHANGE_ANSWER_TYPE';
export const REMOVE_QUESTION = 'QUESTION/REMOVE_QUESTION';
