export const ADD_QUESTION_STARTED = 'QUESTION/ADD_QUESTION_STARTED';
export const ADD_QUESTION_SUCCESS = 'QUESTION/ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAILURE = 'QUESTION/ADD_QUESTION_FAILURE';

export const UPDATE_QUESTION_TEXT_SUCCESS = 'QUESTION/UPDATE_QUESTION_TEXT_SUCCESS';
export const CHANGE_ANSWER_TYPE_SUCCESS = 'QUESTION/CHANGE_ANSWER_TYPE_SUCCESS';
export const REMOVE_QUESTION_STARTED = 'QUESTION/REMOVE_QUESTION_STARTED';
export const REMOVE_QUESTION_SUCCESS = 'QUESTION/REMOVE_QUESTION_SUCCESS';
export const REMOVE_QUESTION_FAILURE = 'QUESTION/REMOVE_QUESTION_FAILURE';
